version: '3'
services:
  temperature:
    image: 'diwise/api-temperature:latest'
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - postgresdb
    links:
      - rabbitmq
      - postgresdb
    environment:
      TEMPERATURE_DB_HOST: 'postgresdb'
      TEMPERATURE_DB_USER: 'testuser'
      TEMPERATURE_DB_NAME: 'temperature'
      TEMPERATURE_DB_PASSWORD: 'testpass'
      TEMPERATURE_DB_SSLMODE: 'disable'
      TEMPERATURE_API_PORT: '8282'
      RABBITMQ_HOST: 'rabbitmq'
      
    ports:
      - '8282:8282'


  deviceregistry:
    image: 'ghcr.io/diwise/iot-device-registry:prod-80fc3d1307891da2494602f8b3766bcef59a7811'
    restart: always
    environment:
      DIWISE_SQLDB_HOST: 'postgresdb'
      DIWISE_SQLDB_USER: 'testuser'
      DIWISE_SQLDB_NAME: 'temperature'
      DIWISE_SQLDB_PASSWORD: 'testpass'
      DIWISE_SQLDB_SSLMODE: 'disable'
      RABBITMQ_HOST: 'rabbitmq'
      SERVICE_PORT: '8990'
      
    ports:
      - '8990'


  federation:
    image: 'ghcr.io/diwise/api-graphql:prod-10f7bb569256a100d2d6df73c12ddc31c30f14c5'
    restart: always
    depends_on:
      - temperature
      - deviceregistry
    environment:
      API_GQL_FEDERATION_PORT: '8080'
      API_GQL_FEDERATION_SVCS: 'temperature:8282,deviceregistry:8990'
    ports:
      - '8989:8080'
    
    
  ingress:
    image: 'ghcr.io/diwise/ingress-trafikverket:prod-22616214cdf589af02e9e08650d444d6591852b8'
    restart: always
    depends_on:
      - temperature
    links:
      - rabbitmq
    environment:
      TFV_API_AUTH_KEY: ${TFV_API_AUTH_KEY}
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_USER: 'user'
      RABBITMQ_PASS: 'bitnami'
  
  
  postgresdb:
    image: 'ghcr.io/diwise/test-db-postgresql:prod-824e7cffd65dd3766c88441a48cffd5b2acd55f2'
    restart: always
    environment:
      POSTGRES_DB: 'temperature'
      POSTGRES_USER: 'testuser'
      POSTGRES_PASSWORD: 'testpass'
    ports:
      - '5432'


  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369'
      - '5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'

volumes:
  rabbitmq_data:
    driver: local
