version: '3'
services:
  temperature:
    image: 'diwise/api-temperature:latest'
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - postgresdb
    links:
      - rabbitmq
      - postgresdb
    environment:
      TEMPERATURE_DB_HOST: 'postgresdb'
      TEMPERATURE_DB_USER: 'testuser'
      TEMPERATURE_DB_NAME: 'temperature'
      TEMPERATURE_DB_PASSWORD: 'testpass'
      TEMPERATURE_DB_SSLMODE: 'disable'
      TEMPERATURE_API_PORT: '8282'
      RABBITMQ_HOST: 'rabbitmq'
      
    ports:
      - '8282:8282'


  deviceregistry:
    image: 'diwise/iot-device-registry:latest'
    restart: always
    environment:
      DIWISE_SQLDB_HOST: 'postgresdb'
      DIWISE_SQLDB_USER: 'testuser'
      DIWISE_SQLDB_NAME: 'temperature'
      DIWISE_SQLDB_PASSWORD: 'testpass'
      DIWISE_SQLDB_SSLMODE: 'disable'
      RABBITMQ_HOST: 'rabbitmq'
      SERVICE_PORT: '8990'
      
    ports:
      - '8990'


  federation:
    build:
      context: ..
      dockerfile: ./test/federation/federation-dockerfile
    restart: always
    depends_on:
      - temperature
      - deviceregistry
    environment:
      API_GQL_FEDERATION_PORT: '8989'
      API_GQL_FEDERATION_SVCS: 'temperature:8282,deviceregistry:8990'
    ports:
      - '8989:8989'
    
    
  ingress:
    image: 'diwise/ingress-trafikverket:latest'
    restart: always
    depends_on:
      - temperature
    links:
      - rabbitmq
    environment:
      TFV_API_AUTH_KEY: ${TFV_API_AUTH_KEY}
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_USER: 'user'
      RABBITMQ_PASS: 'bitnami'
  
  
  postgresdb:
    image: 'diwise/testdb-postgres:latest'
    build:
      context: ..
      dockerfile: ./test/database/testdb-dockerfile
    restart: always
    environment:
      POSTGRES_DB: 'temperature'
      POSTGRES_USER: 'testuser'
      POSTGRES_PASSWORD: 'testpass'
    ports:
      - '5432'


  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369'
      - '5672'
      - '25672'
      - '15672'
    volumes:
      - 'rabbitmq_data:/bitnami'

volumes:
  rabbitmq_data:
    driver: local
