version: '3'
services:
  temperature:
    image: 'iot-for-tillgenglighet/api-temperature:latest'
    build:
      context: ..
      dockerfile: ./deployments/Dockerfile
    restart: always
    depends_on:
      - rabbitmq
      - postgresdb
    links:
      - rabbitmq
      - postgresdb
    environment:
      TEMPERATURE_DB_HOST: 'postgresdb'
      TEMPERATURE_DB_USER: 'testuser'
      TEMPERATURE_DB_NAME: 'temperature'
      TEMPERATURE_DB_PASSWORD: 'testpass'
      TEMPERATURE_API_PORT: '8282'
      
    ports:
      - '8282:8282'


  ingress:
    image: 'iot-for-tillgenglighet/ingress-trafikverket:latest'
    restart: always
    depends_on:
      - temperature
    links:
      - rabbitmq
    environment:
      - TFV_API_AUTH_KEY=${TFV_API_AUTH_KEY}
  
  
  postgresdb:
    image: 'iot-for-tillgenglighet/testdb-postgres:latest'
    build:
      context: ..
      dockerfile: ./test/database/testdb-dockerfile
    restart: always
    environment:
      POSTGRES_DB: 'temperature'
      POSTGRES_USER: 'testuser'
      POSTGRES_PASSWORD: 'testpass'
    ports:
      - '5432'


  rabbitmq:
    image: 'bitnami/rabbitmq:3.7'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    volumes:
      - 'rabbitmq_data:/bitnami'

volumes:
  rabbitmq_data:
    driver: local
